name: CMake on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install ninja
        choco install openssl

    - name: Download and Build libuv
      run: |
        git clone https://github.com/libuv/libuv.git
        cd libuv
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        cmake --build . --config Release
        cd ..
        mkdir C:/libuv
        copy build/Release/uv.lib C:/libuv/
        copy -r include C:/libuv/

    - name: Configure CMake for XMRig
      run: cmake -B ${{ github.workspace }}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DUV_LIBRARY=C:/libuv/uv.lib -DUV_INCLUDE_DIR=C:/libuv/include

    - name: Build XMRig
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-windows
        path: ${{ github.workspace }}/build/Release/xmrig.exe
